---
title: "TIdyTuesday European Energy"
author: "Jeff Grayum"
date: "12/14/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Libraries
```{r}
library(tidyverse)
library(tidytuesdayR)
library(ggthemes)
library(scales)
library(tvthemes)
library(tidytext)
```

Loading datasets
```{r}
tuesdata <- tidytuesdayR::tt_load('2020-08-04')

energy_types <- tuesdata$energy_types

country_totals <- tuesdata$country_totals
```


Exploring the data, some visualizations.
```{r}
energy_types %>%
  view()

energy_types %>%
  str()

energy_types %>%
  distinct(country_name)

energy_types %>%
  count(type, sort = TRUE)

types_pivoted <- energy_types %>%
  pivot_longer(cols = c("2016", "2017", "2018"), #cols = starts_with("2") works too!
               names_to = "year", #creats title for "years" column
               values_to = "gigawatt_hours") %>%  #creates title for "values" column
  view()

types_pivoted %>%
  group_by(country) %>%
  ggplot(aes(year, value, fill = type)) +
  geom_col() +
  facet_wrap(~ country_name, scales = "free_y") +
  labs(title = "How are European countries generating energy?",
       x = "",
       y = "", 
       fill = "Type") +
  theme_fivethirtyeight() +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman")) 

```

That was a bit of a fail.. David's take.
Some ideas:  
-A map (no animation since we only have three years worth of data) 
-Graph of energy consumption by type over time
-Exports, imports, etc.
```{r}
energy_types %>% 
  count(level, sort = TRUE)

energy_types %>%
  count(level, type, sort = TRUE) #All level 2's from Pumped Hydro power.

energy_types %>%
  count(country_name, sort = TRUE)

```

```{r}
#UK comes up as country_name = NA.  Will replace NA's with United Kingom with this trick!

energy_types <- tuesdata$energy_types %>%
  pivot_longer(cols = starts_with("2"),
               names_to = "year",
               values_to = "gigawatt_hours") %>%
  mutate(year = as.integer(year)) %>%
  replace_na(list(country_name = "United Kingdom"))

europe_totals <- energy_types %>%
  filter(level == "Level 1") %>%
  group_by(year, type) %>%
  summarize(total_power = sum(gigawatt_hours)) %>%
  ungroup() %>%
  mutate(type = fct_reorder(type, total_power, sum)) 

europe_totals %>%
  ggplot(aes(year, total_power, fill = type)) +
  geom_col() +
  scale_y_continuous(labels = comma) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman")) +
  labs(title = "How are European countries generating energy?",
       x = "Year",
       y = "Total power (gigawatt hrs)",
       fill = "Type of power")

europe_totals %>%
  ggplot(aes(year, total_power)) +
  geom_col() +
  scale_y_continuous(labels = comma) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman")) +
  labs(title = "How are European countries generating energy?",
       x = "",
       y = "Total power (gigawatt hrs)") +
  facet_wrap(~ type,
             scales = "free_y")


europe_totals %>%
  filter(year == 2018) %>%
  mutate(type = fct_reorder(type, total_power, sum)) %>%
  ggplot(aes(total_power, type)) +
  geom_col() +
  scale_x_continuous(labels = comma) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman")) +
  labs(title = "How are European countries generating energy in 2018?",
       x = "Total power (gigawatt hrs)",
       y = "")
  
```


```{r}
#A great demo of how to use reorder_within()
energy_types %>%
  filter(level == "Level 1",
         year == 2018,
         gigawatt_hours > 0, 
         type != "Other") %>%
  group_by(type) %>%
  mutate(country_name = fct_lump(country_name, 10, w = gigawatt_hours)) %>%
  mutate(country_name = reorder_within(country_name, gigawatt_hours, type, fun = sum),
         type = fct_reorder(type, -gigawatt_hours, sum)) %>%
  ggplot(aes(gigawatt_hours, country_name)) +
  geom_col(width = 0.7) +
  scale_x_continuous(labels = comma) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman")) +
  labs(title = "Energy production in European countries in 2018",
       x = "Power produced (gigawatt hrs)",
       y = "") +
  scale_y_reordered() +
  facet_wrap(~type, scales = "free")

#you can use slice(13) to see what's in row 13!
#if you want to replace uk with gb for ggflag, do this!
##mutate(country = fct_recode(country, gb = "uk"))


devtools::install_github("rensa/ggflags")
 
```


Let's look at changes over time!!
```{r}
energy_types %>%
  filter(gigawatt_hours > 0) %>%
  filter(year %in% c(2016, 2018),
         type == "Nuclear") %>%
  ggplot(aes(year, gigawatt_hours, color = country)) +
  geom_line(size = 1.1, aes(group = country)) +
  geom_text(aes(label = country_name), hjust = 1,
            check_overlap = TRUE) +
  scale_y_log10(labels = comma) +
  scale_x_continuous(breaks = c(2016, 2018),
                     limits = c(2015, 2019)) +
  labs(title = "Changes in nuclear energy production in European countries",
       x = "Year",
       y = "Nuclear energy produced (gigawatt hrs)",
       color = NULL) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"),
        legend.position = "none") 

```


```{r}
country_totals %>%
  view()
```

